<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20170702054602 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE cloudframe_leavemanagement_domain_model_employee CHANGE gender gender TINYINT(1) DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE contactnumber contactnumber VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE cloudframe_leavemanagement_domain_model_employee ADD CONSTRAINT FK_EE8F7BC847A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE cloudframe_leavemanagement_domain_model_employee DROP FOREIGN KEY FK_EE8F7BC847A46B0A");
		$this->addSql("ALTER TABLE cloudframe_leavemanagement_domain_model_employee CHANGE gender gender TINYINT(1) NOT NULL, CHANGE address address VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE contactnumber contactnumber VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci");
	}
}